### ISSUE TITLE
Uses too much memory to compile under GHC 7.10.1

### ISSUE THREAD

**Issue by bananagram** [haskell-opengl/OpenGLRaw#28] opened 2015-04-13 00:23 UTC
When compiling OpenGLRaw, GHC 7.10 will bloat when it reaches [199 of 520] Graphics.Rendering.OpenGL.Raw.Functions, running out of memory on my 4GB system. Before 199 it uses a small amount of memory. I've tried it with -O0 and it compiles, though, only growing to 600M.

**Comment by serprex** [comment] 2015-04-13 02:05
#26

**Comment by svenpanne** [comment] 2015-04-13 06:42
Closing as a duplicate of #26.

(Is there still no real way to do this on GitHub?)

**Closed by svenpanne** 2015-04-13 06:42 UTC

**Comment by phaazon** [comment] 2015-04-13 08:10
@svenpanne Attach a `duplicate` label :)
