### ISSUE TITLE
Missing C library: GL

### ISSUE THREAD

**Issue by Fresheyeball** [haskell-opengl/OpenGLRaw#34] opened 2016-12-21 07:55 UTC
```
 Configuring OpenGLRaw-3.2.4.0...
    setup-Simple-Cabal-1.24.0.0-ghc-8.0.1: Missing dependency on a foreign
    library:
    * Missing C library: GL
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```
for the life of me I can't get passed this one. I've installed mesa, glut, everything I've read for the library. I've installed cabal and stack, both from haskell-platform, and nix, and I've passed the --extra-lib-dirs. Nothing.

**Comment by svenpanne** [comment] 2016-12-21 09:12
Something seems to be strange with your OpenGL setup. Could you try the following?

```sh
echo 'int main(int argc, char** argv) { return 0; }' > blah.c
gcc blah.c -lGL
```

This is basically (part of) what stack/cabal does under the hood, and it should compile/link without problems. Which platform/distribution are you using exactly?

**Comment by Fresheyeball** [comment] 2016-12-21 17:33
Ok so I ran that script and got back a `a.out` file, and no console output. Here is some info on my system

Ubuntu 14.04 (KDE plasma desktop)
cabal-install 1.24.0.1 (installed with nix)
ghc 8.0.1 (installed with nix)
stack 1.2.0 x86_64 (installed with nix)
gcc 4.8.4 (installed with apt)

I've installed:
libgl1-mesa-glx:i386
libopengl-dev
freeglut3
freeglut3-dev
---

Thank you for your help. Yeah, something is off on my end, but I don't know what, and don't have the know how to figure it out (I don't know what cabal is doing under the covers).

**Comment by svenpanne** [comment] 2016-12-21 21:01
Hmmm, that's weird... What's the output of`:

```sh
ldd $(which glxgears)
```

There should be a line with `libGL.so` in the output. You can then try:

```sh
strace -e trace=all -s 9999 -f -o trace.log cabal ...
```

where `cabal ...` is the command you are using to build OpenGLRaw (could be `stack ...`, too). Then you can look into `trace.log` to see where cabal/stack is looking for `libGL.so`.

I've never heard of a similar problem, but I've never used nix. An alternative approach would be: Nuke your cabal-install/ghc/stack and install stack directly as explained in https://docs.haskellstack.org/en/stable/install_and_upgrade/#ubuntu. Then a `stack init && stack build` should work out of the box, at least it works for me on Ubuntu 16.04/16.10.

**Comment by Fresheyeball** [comment] 2016-12-21 21:04
`ldd $(which glxgears)`

```
	linux-vdso.so.1 =>  (0x00007fff56fb5000)
	libGL.so.1 => /usr/lib/nvidia-367/libGL.so.1 (0x00007fe6a5fb8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe6a5cb2000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe6a597c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe6a55b7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe6a53b3000)
	libGLX.so.0 => /usr/lib/nvidia-367/libGLX.so.0 (0x00007fe6a5181000)
	libGLdispatch.so.0 => /usr/lib/nvidia-367/libGLdispatch.so.0 (0x00007fe6a4e98000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe6a4c79000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563ace185000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe6a4a66000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe6a4862000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe6a465c000)
```

The output of `trace.log` is massive, I'm not sure what to look for in there.

**Comment by Fresheyeball** [comment] 2016-12-21 21:05
I've also tried using stack and cabal installed via `haskell-platform`, no change.

**Comment by svenpanne** [comment] 2016-12-21 22:08
The line

```
libGL.so.1 => /usr/lib/nvidia-367/libGL.so.1 (0x00007fe6a5fb8000)
```

reminds me of https://github.com/haskell-opengl/OpenGLRaw/issues/25. Some combinations of NVIDIA drivers and old Ubuntu versions can trigger this problem, too, obviously. You can either symlink the OpenGL libs to a more standard location or tell cabal/stack via `--extra-lib-dirs=/usr/lib/nvidia-367` or https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#extra-include-dirsextra-lib-dirs about the NVIDIA installation path.

**Comment by Fresheyeball** [comment] 2016-12-22 05:37
For the love of bob and all that is moly, that worked!

**Comment by Fresheyeball** [comment] 2016-12-22 05:40
Actually may have gotten over excited. It got past that one, but now I'm getting this one:
```
Configuring GLURaw-2.0.0.2...
    setup-Simple-Cabal-1.24.0.0-ghc-8.0.1: Missing dependency on a foreign
    library:
    * Missing C library: GLU
```

**Comment by svenpanne** [comment] 2016-12-25 16:59
This is again quite obscure, headers below `/usr/include` should always be found. Somehow I have the impression that all the problems are caused by `nix`, it doesn't seem to work well with `cabal` and `stack`, at least not when native libraries are involved. Perhaps you can try to find some help on `nix` mailing lists and forums? I've never used it, so all I can do is do some guessing...

If you are using `stack`: Try to use Stackage nightly instead of LTS, it contains a more recent version of [`GLURaw`](https://www.stackage.org/nightly-2016-12-23/package/GLURaw-2.0.0.3)  which doesn't need the GLU header. If that doesn't help: Use `strace` to figure out how the C compiler is called and where it looks for `GL/glu.h`.

**Comment by Fresheyeball** [comment] 2016-12-29 05:02
ok, so I tried nightly and it did get further, but still failed:

`stack install --extra-lib-dirs=/usr/lib/nvidia-367 --extra-lib-dirs=/usr/lib/x86_64-linux-gnu  --resolver nightly-2016-12-28`

```
Warning: File listed in gloss-stack/gloss-stack.cabal file does not exist: README.md
gloss-stack-0.1.0.0: configure
Configuring gloss-stack-0.1.0.0...
gloss-stack-0.1.0.0: build
Preprocessing executable 'gloss-stack' for gloss-stack-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/gloss-stack/gloss-stack-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/gloss-stack/gloss-stack ...
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__tdelete@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__libc_vfork@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__getrlimit@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__tfind@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__h_errno@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__twalk@GLIBC_PRIVATE'
/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libpthread.so.0: undefined reference to `__tsearch@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
Warning: File listed in gloss-stack/gloss-stack.cabal file does not exist: README.md

--  While building package gloss-stack-0.1.0.0 using:
      /home/isaac/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build exe:gloss-stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by svenpanne** [comment] 2016-12-29 07:01
I've got no idea what the `gloss-stack` package is, I can't find it on Hackage/Stackage. Anyway, the `gloss-stack.cabal` file seems to mention `README.md`, which is not there, so the package is effectively broken. But that's an issue for the `gloss-stack` bug tracker. And the linker trouble seems to be once again caused by nix, so either nix itself or your installation of it seems to be broken.

Regarding the OpenGL packages, everything seems to work now, so I'm closing this ticket.

**Closed by svenpanne** 2016-12-29 07:01 UTC

**Comment by Fresheyeball** [comment] 2016-12-29 18:14
Fair enough! These low level issues are obscure indeed, and documentation is scarce. You have been tremendously helpful. I feel like I can continue with my experiments, thanks to your support. Thank you! :100:

**Comment by smelc** [comment] 2020-03-12 21:32
Without `nix`, fixed the `Missing C library: GL` error with:

```
sudo apt install libgl1-mesa-dev
```

Then a second error showed up: `Missing (or bad) C library: GLU`. Solved it with:

```
sudo apt install freeglut3{,-dev}
```
